name: Build

on:
  push:
    branches:
      - main
    paths:
      - "sonar-cloud/**"
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  sonarcloud:
    if: startsWith(github.head_ref, 'FE_') && github.event.pull_request.merged == false || ( github.event_name == 'push' )
    name: SonarCloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sonar-cloud
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better analysis relevance

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Run Tests
        run: npm test

      - name: SonarCloud Scan for Pull Request
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./sonar-cloud # Specify the correct directory
          args: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.branch.name=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  branchAnalysis:
    if: github.event.pull_request.merged == true
    name: Branch Analysis on PR merge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sonar-cloud
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better analysis relevance

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test

      - name: SonarCloud Scan for Main Branch
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./sonar-cloud # Specify the correct directory
          args: >
            -Dsonar.branch.name=main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
